services:
  - type: web
    name: mental-health-chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
    startCommand: gunicorn app:app --chdir backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PIP_VERSION
        value: 23.0.1 